services:
- docker

image:
- Visual Studio 2017
- Ubuntu

install:
  - git submodule update --init
  - cmd: set PATH="C:\Program Files\LLVM\bin";C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%
  - cmd: C:\Python36-x64\python -m pip install jinja2 nose pycodestyle
  
build_script:
  - cmd: python scripts\build.py -t --python-path "C:\\Python36-x64\\python"
  - sh: docker pull ffig/ffig-base
  - sh: docker build . -t ffig-ci
  - sh: docker run ffig-ci /bin/bash -c "./scripts/build.py -t --python-path python2 --venv"
  - sh: docker run ffig-ci /bin/bash -c "./scripts/build.py -t --python-path python3 --venv"

