# Modify this line to test Travis Integration ... 
sudo: required

language: python

cache:
  directories:
    - /home/travis/docker/

env:
  global:
    - DOCKER_REPOSITORY=jbcoe/ffig
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz
   
services:
  - docker

install:
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} .

script:
  - docker run ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} /bin/bash -c "./scripts/build.py -t"
  - docker run ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} /bin/bash -c "./scripts/build.py -t --python-path python3"

notifications:
  slack:
    rooms:
      - c-api:ZTxxqvEcr25iaaB8XBS7luaA#travis-ci
