# Modify this line to test Travis Integration ... 
sudo: required

language: python

matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker
      install:
        - docker pull ffig/ffig-base
        - docker build . -t ffig-ci
      before_install:
        - pip install pep8
      script:
        - docker run ffig-ci /bin/bash -c "./scripts/build.py -t --python-path python2 --venv"
        - docker run ffig-ci /bin/bash -c "./scripts/build.py -T \"CPP|MOCKS\" -c ASAN --python-path python2 --venv"
        - docker run ffig-ci /bin/bash -c "./scripts/build.py -t --python-path python3 --venv"
        - docker run ffig-ci /bin/bash -c "./scripts/build.py -T \"CPP|MOCKS\" -c ASAN --python-path python3 --venv"
        - ./scripts/codechecks.py

    - os: osx
      language: generic
      osx_image: xcode8
      install:
        - brew update
        - brew install ninja python3
        - sudo pip2 install --upgrade pip && sudo pip2 install jinja2 nose backports.typing
        - sudo pip3 install --upgrade pip && sudo pip3 install jinja2 nose
        - gem install ffi
      script:
        - ./scripts/build.py -t
        - ./scripts/build.py -t --python-path python3

notifications:
  slack:
    rooms:
      - c-api:ZTxxqvEcr25iaaB8XBS7luaA#travis-ci
